export const UPDATE_ANSWER ='UPDATE_ANSWER';
export const SET_CAMPAIGN ='SET_CAMPAIGN';
export const SET_SCENARIO ='SET_SCENARIO';

export const SET_CHOICES = 'SET_CHOICES';
export const SET_QUESTIONS ='SET_QUESTIONS';
export const SET_QUESTION ='SET_QUESTION';
export const FILTER_QUESTIONS='FILTER_QUESTIONS';
export const RESET_FORM = 'RESET_FORM';

export const FINISHED_FORM = 'FINISHED_FORM';
export const NEW_FORM = 'NEW_FORM';

export const SET_MODE = 'SET_MODE'

export const FETCH_USER ='FETCH_USER';
export const FETCH_FILES = 'FETCH_FILES';

export const SUBMIT_ANSWERS_START ='SUBMIT_ANSWERS_START';
export const SUBMIT_ANSWERS_SUCCESS ='SUBMIT_ANSWERS_SUCCESS';
export const SUBMIT_ANSWERS ='SUBMIT_ANSWERS';
export const SUBMIT_ANSWERS_ERROR ='SUBMIT_ANSWERS_ERROR';

export const CREATE_FILE_START = 'CREATE_FILE_START';
export const CREATE_FILE_SUCCESS = 'CREATE_FILE_SUCCESS';
export const CREATE_FILE_ERROR= 'CREATE_FILE_ERROR';

